### ISSUE TITLE
Update hydrogen to latest version

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chatrix#142]
We're on 0.3.2 and hydrogen is on 0.3.5: https://github.com/vector-im/hydrogen-web/releases

The new releases bring bug fixes and some new features as well.

**Comment by ashfame** [comment]
Updating to 0.3.5 causes an issue with vite that I can't wrap my head around. I had to do it to use my changes on Hydrogen. After running `yarn start`, I run into this:

```
1:28:13 PM [vite] Internal server error: Cannot read properties of undefined (reading 'charCodeAt')
  Plugin: vite:css
  File: /Users/ashfame/git/chatrix/frontend/iframe/styles/theme/theme.css
      at module.exports (/Users/ashfame/git/chatrix/node_modules/postcss-value-parser/lib/parse.js:28:20)
      at new ValueParser (/Users/ashfame/git/chatrix/node_modules/postcss-value-parser/lib/index.js:7:18)
      at ValueParser (/Users/ashfame/git/chatrix/node_modules/postcss-value-parser/lib/index.js:10:10)
      at findAndReplaceUrl (/Users/ashfame/git/chatrix/node_modules/hydrogen-web/scripts/postcss/css-url-to-variables.js:27:20)
      at /Users/ashfame/git/chatrix/node_modules/hydrogen-web/scripts/postcss/css-url-to-variables.js:83:36
      at /Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:72:18
      at /Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:55:18
      at Rule.each (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:41:16)
      at Rule.walk (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:52:17)
      at /Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:60:24
      at Root.each (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:41:16)
      at Root.walk (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:52:17)
      at Root.walkDecls (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/container.js:70:19)
      at Object.Once (/Users/ashfame/git/chatrix/node_modules/hydrogen-web/scripts/postcss/css-url-to-variables.js:83:18)
      at LazyResult.runOnRoot (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/lazy-result.js:337:23)
      at LazyResult.runAsync (/Users/ashfame/git/chatrix/node_modules/vite/node_modules/postcss/lib/lazy-result.js:393:26)
      at async compileCSS (/Users/ashfame/git/chatrix/node_modules/vite/dist/node/chunks/dep-689425f3.js:37463:27)
      at async TransformContext.transform (/Users/ashfame/git/chatrix/node_modules/vite/dist/node/chunks/dep-689425f3.js:37010:55)
      at async Object.transform (/Users/ashfame/git/chatrix/node_modules/vite/dist/node/chunks/dep-689425f3.js:39317:30)
      at async doTransform (/Users/ashfame/git/chatrix/node_modules/vite/dist/node/chunks/dep-689425f3.js:50043:29) (x2)
```

**Comment by ashfame** [comment]
0.3.4 works fine in this regard. Its something in 0.3.4 and 0.3.5 that causes this. No dependencies have changed in `package.json` so this is puzzling.

[See Code changes between 0.3.4 and 0.3.5](https://github.com/vector-im/hydrogen-web/compare/v0.3.4...v0.3.5)
